evorya/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin-evorya/', include('evorya_admin.urls')),
    path('evorya-voters/', include('voters.urls')),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

evorya_admin/urls.py
from django.urls import path, include
from .views import *

app_name = 'admin'
urlpatterns = [
    path('', include([
        path('dashboard-admin/', dashboard_admin__views.DashboardAdminView.as_view(), name='dashboard_admin'),
	])),

    path('account/', include([
        path('', UserListView.as_view(), name='user_list'),
        path('add-user/', AddUserView.as_view(), name='add_user'),
        path('edit-user/', EditUserView.as_view(), name='edit_user'),
        path('delete/<str:nim>/', DeleteUserView.as_view(), name='delete_user'),
        path('import/', ImportUserView.as_view(), name='import_user'),
    ])),

    path('pemilihan/', include([
        path('', PemilihanListView.as_view(), name='pemilihan_list'),
        path('add-voting/', AddPemilihanView.as_view(), name='add_pemilihan'),
        path('edit-voting/', EditPemilihanView.as_view(), name='edit_pemilihan'),
        path('delete/<int:id>/', DeletePemilihanView.as_view(), name='delete_pemilihan'),
        path('<int:pemilihan_id>/kandidat/', TambahKandidatView.as_view(), name='tambah_kandidat'),
        path('<int:pemilihan_id>/kandidat/<int:pk>/edit/', EditKandidatView.as_view(), name='edit_kandidat'),
        path('<int:pemilihan_id>/kandidat/<int:pk>/delete/', DeleteKandidatView.as_view(), name='delete_kandidat'),
        path('<int:pemilihan_id>/atur-pemilih', AturPemilihView.as_view(), name='atur_pemilih'),
    ])),

    path('hasil-pemilihan/', include([
        path('', HasilPemilihanView.as_view(), name='hasil_pemilihan'),
    ])),

    path('suara-mencurigkan/', include([
        path('', SuaraMencurigakanView.as_view(), name='suara_mencurigakan'),
        path('export-mencurigakan/', ExportSuaraMencurigakanCSVView.as_view(), name='export_suara_mencurigakan_csv'),
        path('export/all', ExportSuaraMencurigakanCSVView.as_view(), name='export_all'),
    ]))
]

main/urls.py
from django.urls import path, include
from .views import *

app_name = 'main'
urlpatterns = [
    path('', include([
        path('', RedirectToLoginView.as_view(), name ='redirect_to_login'),
        path('login/', LoginView.as_view(), name='login'),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('profile/<str:nim>/', ProfileView.as_view(), name='user_profile'),
        path('profile/<str:nim>/ubah-password/', ProfileView.as_view(), name='user_profile_with_password_prompt'),
    ])),
]

voters/urls.py
from django.urls import path, include
from .views import *

app_name = 'voters'

urlpatterns = [
    path('', include([
        path('home/', home_views.HomeView.as_view(), name='home'),
        path('vote/<int:pemilihan_id>/', vote_views.VotePageView.as_view(), name='vote_page'),
        path('vote/<int:pemilihan_id>/send_token/', vote_views.SendTokenView.as_view(), name='send_token'),
        path('vote/<int:pemilihan_id>/submit/', vote_views.SubmitVoteView.as_view(), name='submit_vote'),
        path('hasil/<int:pemilihan_id>/', home_views.HomeView.as_view(), name='hasil_pemilihan'),
	])),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}E-Voting PEMIRA UNJAYA{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">

    {% block extra_css %}{% endblock %}
</head>

<body class="bg-light">

    {% if user.is_authenticated %}
    <!-- Navbar -->
    <div class="navbar navbar-expand fixed-top bg-white shadow-sm py-2 d-md-none"
        style="z-index: 1030;">
        <div class="container-fluid px-3 d-flex align-items-center justify-content-center" style="height: 100%;">
            <button class="btn me-auto btn-info" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu"
                aria-controls="sidebarMenu">
                <i class="bi bi-list"></i>
            </button>
    
            <div class="dropdown ms-auto">
                <a href="#" class="d-flex align-items-center text-decoration-none" id="userDropdown"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ user.photo_profile.url }}" alt="Foto Profil" class="rounded-circle me-2"
                        style="width: 30px; height: 30px; object-fit: cover;">
                    <div class="d-block">
                        <div class="fw-semibold text-dark" style="font-size: 14px;">{{ user.nim }}</div>
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                    <li>
                        <a href="#" class="dropdown-item">
                            <span class="fw-semibold d-block" style="font-size: 12px;">{{ user.full_name }}</span>
                            <small class="text-muted d-block" style="font-size: 11px;">{{ user.email }}</small>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'main:user_profile' user.nim %}">
                            <i class="bi bi-person-circle me-2"></i> Profil Saya</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item text-danger" href="{% url 'main:logout' %}">
                            <i class="bi bi-box-arrow-right me-2"></i>Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
    
    <!-- Sidebar-->
    <nav class="sidebar d-none d-md-flex flex-column flex-shrink-0 p-3 bg-white">
        <a href="#" class="d-flex mb-2 justify-content-center align-items-center link-body-emphasis text-decoration-none">
            <h6 class="text-center align-items-center py-2 mb-0">E-Voting PEMIRA UNJAYA</h6>
        </a>
        <hr class="mt-2 mb-3">
        <ul class="nav nav-pills flex-column mb-auto">
            {% if user.role == 'admin' %}
            <li class="nav-item mb-1">
                <a class="nav-link {% if request.resolver_match.url_name == 'dashboard_admin' %}active{% endif %}"
                    href="{% url 'admin:dashboard_admin' %}">
                    <i class="bi bi-speedometer2 me-2"></i> Dashboard
                </a>
            </li>
            <li class="nav-item mb-1">
                <a class="nav-link {% if request.resolver_match.url_name == 'user_list' %}active{% endif %}"
                    href="{% url 'admin:user_list' %}">
                    <i class="bi bi-person-fill-gear me-2"></i> Data Pemilih
                </a>
            </li>
            <li class="nav-item mb-1">
                <a class="nav-link {% if request.resolver_match.url_name == 'pemilihan_list' %}active{% endif %}"
                    href="{% url 'admin:pemilihan_list' %}">
                    <i class="bi bi-ui-checks-grid me-2"></i> Pemilihan
                </a>
            </li>
            <li class="nav-item mb-1">
                <a class="nav-link {% if request.resolver_match.url_name == 'hasil_pemilihan' %}active{% endif %}"
                    href="{% url 'admin:hasil_pemilihan' %}">
                    <i class="bi bi-bar-chart-line-fill me-2"></i> Hasil Pemilihan
                </a>
            </li>
            <li class="nav-item mb-1">
                <a class="nav-link d-flex justify-content-between align-items-center {% if request.resolver_match.url_name == 'suara_mencurigakan' %}active{% endif %}"
                    href="{% url 'admin:suara_mencurigakan' %}">
                    <div>
                        <i class="bi bi-exclamation-triangle-fill me-2 text-danger"></i> Suara Mencurigakan
                    </div>
                    {% if total_kecurangan > 0 %}
                    <span class="badge bg-danger">{{ total_kecurangan }}</span>
                    {% endif %}
                </a>
            </li>              
            {% if user.is_staff == False %}
            <li class="nav-item mb-1">
                <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"
                    href="{% url 'voters:home' %}">
                    <i class="bi bi-person-lines-fill me-2"></i> Dashboard Voter
                </a>
            </li>
            {% endif %}
            {% else %}
            <li class="nav-item mb-1">
                <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"
                    href="{% url 'voters:home' %}">
                    <i class="bi bi-house-door-fill me-2"></i> Home
                </a>
            </li>
            {% endif %}
        </ul>        
        <div class="mt-auto p-3 border-top">
            <div class="d-flex align-items-center mb-3">
                <a href="{% url 'main:user_profile' user.nim %}" class="d-flex align-items-center text-decoration-none" aria-expanded="false">
                    <img src="{{ user.photo_profile.url }}" alt="Foto Profil" class="rounded-circle me-2"
                        style="width: 40px; height: 40px; object-fit: cover;">
                    <div class="text-decoration-none">
                        <span class="fw-semibold d-block text-dark" style="font-size: 14px;">{{ user.full_name }}</span>
                        <small class="text-muted d-block" style="font-size: 12px;">{{ user.email }}</small>
                    </div>
                </a>
            </div>
            <a href="{% url 'main:logout' %}" class="btn btn-danger w-100 gap-2 py-1"><i class="bi bi-box-arrow-right me-2"></i> Logout</a>
        </div>
    </nav>
    
    <!-- Sidebar Mobile Offcanvas-->
    <nav class="offcanvas offcanvas-start d-md-none bg-white p-3" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
        <a href="#" class="d-flex offcanvas-header justify-content-center align-items-center link-body-emphasis text-decoration-none p-2">
            <h6 class="text-center align-items-center mb-0">E-Voting PEMIRA UNJAYA</h6>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </a>
        <hr class="mt-2 mb-2">
        <ul class="nav nav-pills flex-column mb-auto">
            {% if user.role == 'admin' %}
            <li class="nav-item mb-1">
                <a class="nav-link" href="{% url 'admin:dashboard_admin' %}"><i class="bi bi-speedometer2 me-2"></i> Dashboard</a>
            </li>
            <li class="nav-item mb-1">
                <a class="nav-link" href="{% url 'admin:user_list' %}"><i class="bi bi-person-fill-gear me-2"></i> Data Pemilih</a>
            </li>
            <li class="nav-item mb-1">
                <a class="nav-link" href="{% url 'admin:pemilihan_list' %}"><i class="bi bi-ui-checks-grid me-2"></i> Pemilihan</a>
            </li>
            <li class="nav-item mb-1">
                <a class="nav-link" href="{% url 'admin:hasil_pemilihan' %}"><i class="bi bi-bar-chart-line-fill me-2"></i> Hasil Pemilihan</a>
            </li>
            {% if user.is_staff == False %}
            <li class="nav-item mb-1">
                <a class="nav-link" href="{% url 'voters:home' %}"><i class="bi bi-person-lines-fill me-2"></i> Dashboard Voter</a>
            </li>
            {% endif %}
            {% else %}
            <li class="nav-item mb-1">
                <a class="nav-link" href="{% url 'voters:home' %}"><i class="bi bi-house-door-fill me-2"></i> Home</a>
            </li>
            {% endif %}
        </ul>
        <div class="mt-auto p-3 border-top">
            <div class="d-flex align-items-center mb-3">
                <a href="{% url 'main:user_profile' user.nim %}" class="d-flex align-items-center text-decoration-none" aria-expanded="false">
                    <img src="{{ user.photo_profile.url }}" alt="Foto Profil" class="rounded-circle me-2"
                        style="width: 30px; height: 30px; object-fit: cover;">
                    <div class="text-decoration-none">
                        <span class="fw-semibold d-block text-dark" style="font-size: 12px;">{{ user.full_name }}</span>
                        <small class="text-muted d-block" style="font-size: 11px;">{{ user.email }}</small>
                    </div>
                </a>
            </div>
            <a href="{% url 'main:logout' %}" class="btn btn-danger w-100 gap-2 py-1"><i class="bi bi-box-arrow-right me-2"></i>
                Logout</a>
        </div>
    </nav>
    {% endif %}

    <div class="{% if user.is_authenticated %}with-sidebar p-4{% else %} container-fluid {% endif %}">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    {% block extra_js %}{% endblock %}
</body>

</html>